# Generated by Django 5.2.16 on 2026-07-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=150)),
                ('nome_fantasia', models.CharField(blank=True, max_length=150)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site', models.CharField(blank=True, max_length=150)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('bairro', models.CharField(blank=True, max_length=80)),
                ('cidade', models.CharField(blank=True, max_length=80)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('recibo_prefixo', models.CharField(default='REC', max_length=10)),
                ('intervalo_agenda', models.IntegerField(default=30)),
                ('inicio_expediente', models.TimeField()),
                ('fim_expediente', models.TimeField()),
                ('smtp_servidor', models.CharField(blank=True, max_length=100)),
                ('smtp_porta', models.IntegerField(default=587)),
                ('smtp_email', models.EmailField(blank=True, max_length=254)),
                ('smtp_senha', models.CharField(blank=True, max_length=100)),
                ('ssl', models.BooleanField(default=True)),
                ('token_whatsapp', models.CharField(blank=True, max_length=250)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
