# Generated by Django 5.2.16 on 2026-08-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('GERAL', 'Multidisciplinar / Geral'), ('MENTAL', 'Saúde Mental (Psicologia/Psiquiatria)'), ('FISICA', 'Saúde Física (Fisioterapia/Ortopedia)'), ('SOCIAL', 'Bem-Estar Social / Familiar'), ('ODONTO', 'Odontologia / Estética'), ('NUTRICAO', 'Nutrição / Acompanhamento')], default='GERAL', max_length=20)),
                ('logo_personalizado', models.ImageField(blank=True, null=True, upload_to='logos_clinicas/')),
                ('cor_primaria', models.CharField(blank=True, help_text='Exemplo: #0284C7', max_length=7)),
            ],
        ),
    ]
