# Generated by Django 5.2.16 on 2026-08-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_cliente_bairro_cliente_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='sessoes_realizadas',
            field=models.IntegerField(default=0),
        ),
    ]
