# Generated by Django 5.2.16 on 2026-08-02 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_sessoes_realizadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dias_vencimento',
            field=models.PositiveIntegerField(default=5, help_text='Quantidade de dias após o agendamento para o vencimento da fatura'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Suelen Garcia de Almeida'),
        ),
    ]
