# Generated by Django 5.2.16 on 2026-07-31 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queixa', models.TextField(blank=True)),
                ('anamnese', models.TextField(blank=True)),
                ('evolucao', models.TextField(blank=True)),
                ('procedimentos', models.TextField(blank=True)),
                ('conduta', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atendimento', to='agenda.agendamento')),
            ],
        ),
    ]
